# Generated by Django 2.1.3 on 2019-02-20 05:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Producto')),
                ('image', models.ImageField(upload_to='galery', verbose_name='Imagen')),
                ('productId', models.CharField(max_length=10, verbose_name='Clave de producto')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripcion corta')),
                ('largeDescription', ckeditor.fields.RichTextField(verbose_name='Descripcion detallada')),
                ('prize', models.FloatField(verbose_name='Precio')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('paypalButton', models.TextField(verbose_name='Botón Paypal')),
                ('available', models.BooleanField(verbose_name='Disponible')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created'],
            },
        ),
    ]
