# Generated by Django 2.1.3 on 2019-02-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paypalButton',
            field=models.TextField(default='asd', verbose_name='Botón Paypal'),
            preserve_default=False,
        ),
    ]
