# Generated by Django 2.1.3 on 2019-02-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_product_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='largeDescription',
            field=models.TextField(default=' ', verbose_name='Descripcion detallada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descripcion corta'),
        ),
    ]
