# Generated by Django 2.1.3 on 2019-02-12 20:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20190212_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion corta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='largeDescription',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion detallada'),
        ),
    ]
