# Generated by Django 2.1.3 on 2019-02-20 05:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Texto Inicio',
                'verbose_name_plural': 'Textos inicio',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('image', models.ImageField(upload_to='', verbose_name='imágen inicio')),
            ],
            options={
                'verbose_name': 'imágen Inicio',
                'verbose_name_plural': 'imagenes inicio',
            },
        ),
    ]
